{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeCannot read property '0' of undefined","stack":"TypeError: Cannot read property '0' of undefined\n    at Function.init (/Users/dip/dipankar/dutils/dist/dtelemetry.js:34:36)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:17:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:17:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:17:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:17:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:17:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:17:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:17:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:18:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:18:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:25:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:43:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:43:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Test Fail: Observed:Validation failed: x must be a arry of objects, expected:Validation failed: x must be a array of objects"}
{"level":"error","message":"[ERROR] \n    -----------------------------------------------\n        U T report\n    -----------------------------------------------\n    Total TC: 24\n    Passed: 23\n    Failed: 1\n    -----------------------------------------------\n    "}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:46:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] \n    -----------------------------------------------\n        U T report\n    -----------------------------------------------\n    Total TC: 24\n    Passed: 24\n    Failed: 0\n    -----------------------------------------------\n    "}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:46:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:46:16)\n    at Module._compile (internal/modules/cjs/loader.js:1147:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Test Fail: Observed:Validation failed: roll must be a string, expected:true"}
{"level":"error","message":"[ERROR] Test Fail: Observed:Validation failed: roll is null or undefined, expected:true"}
{"level":"error","message":"[ERROR] Test Fail: Observed:Validation failed: x is missing from input , expected:Validation failed: x is null or undefined"}
{"level":"error","message":"[ERROR] Test Fail: Observed:Validation failed: x must be a boolean, expected:Validation failed: x must be a isBoolean"}
{"level":"error","message":"[ERROR] Test Fail: Observed:Validation failed: roll is missing from input , expected:true"}
{"level":"error","message":"[ERROR] Test Fail: Observed:Validation failed: x is missing from input , expected:Validation failed: x is missing from input"}
{"level":"error","message":"[ERROR] Test Fail: Observed:Validation failed: roll is missing from input , expected:Validation failed: roll is missing from input"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x is missing from input >, expected:<Validation failed: x is missing from input>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: roll is missing from input >, expected:<Validation failed: roll is missing from input>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: email must be email>, expected:<true>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: email must be email>, expected:<xx>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: tags must be a array>, expected:<xx>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: The x field is required>, expected:<Validation failed: x is missing from input>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: The x field must not empty>, expected:<Validation failed: x Must not empty>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: The x field must not empty>, expected:<Validation failed: x Must not empty>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: The roll field is required>, expected:<Validation failed: roll is missing from input>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of [1,2]>, expected:<true>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of [1,2]>, expected:<true>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of [1,2]>, expected:<true>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of [1,2]>, expected:<true>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of [1,2]>, expected:<true>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of [1,2]>, expected:<x should be either of [1,2]>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of [1,2]>, expected:<x should be either of [1,2]>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of [1,2]>, expected:<x should be either of [1,2]>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<true>, expected:<Validation failed: x should be either of [1,2]>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of 1,2>, expected:<Validation failed: x should be either of [1,2]>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of 1,2>, expected:<Validation failed: x should be either of [1,2]>"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<true>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:23:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of 1,2>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:24:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of 1,2>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:25:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<true>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:23:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of 1,2>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:24:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: x should be either of 1,2>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:25:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: The x field is required>, expected:<#> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:24:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: The x field is required>, expected:<#> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:24:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<true>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:27:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: The x field is required>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:28:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<true>, expected:<Validation failed: The x field is required> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:29:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<true>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:29:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<true>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:29:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<true>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:29:4)"}
{"level":"error","message":"[ERROR] Test Fail: Observed:<Validation failed: Found Invalid Rule [required|in:1,2]>, expected:<Validation failed: x should be either of [1,2]> at at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:29:4)"}
